// Traductions FR/EN du bot. La langue est choisie selon le rôle du membre.
const T = {
  fr: {
    noDescription: "Pas de description disponible.",
    unknown: "N/A",
    serial: "Serial",
    region: "Région",
    developer: "Développeur",
    publisher: "Éditeur",
    genres: "Genres",
    release: "Sortie",
    rating: "Classification",
    notFound: "Jeu introuvable",
    serialNotFound: (s) => `Aucun jeu trouvé avec le serial \`${s}\`.`,
    gameNotFound: (q) => `Aucun jeu trouvé pour « ${q} ».`,
    error: "Une erreur est survenue.",
    games: "jeux",
    systems: "systèmes",
    lastUpdated: "Dernière mise à jour",
    version: "Version",
    author: "Auteur",
    systemsField: "Systèmes",
    downloads: "Téléchargements",
    viewGame: "Voir la fiche",
    moreResults: (n) => `+ ${n} autre(s) résultat(s) — affinez votre recherche`,
    randomTitle: "Jeu aléatoire",
    statsTitle: "Statistiques NDS-Shop",
    teamTitle: "Équipe NDS-Shop",
    teamEmpty: "Aucun membre enregistré.",
    status: {
      online: "En ligne",
      idle: "Absent",
      dnd: "Ne pas déranger",
      offline: "Hors ligne",
    },
    helpTitle: "Commandes NDS-Shop",
    suggestSent: "Suggestion envoyée dans #suggestions !",
    reportSent: "Rapport envoyé dans #bug-reports !",
    suggestTitle: "💡 Suggestion",
    reportTitle: "🐛 Rapport de bug",
    byUser: "par",
    newGamesTitle: "🆕 Nouveau jeu disponible",
  },
  en: {
    noDescription: "No description available.",
    unknown: "N/A",
    serial: "Serial",
    region: "Region",
    developer: "Developer",
    publisher: "Publisher",
    genres: "Genres",
    release: "Release",
    rating: "Rating",
    notFound: "Game not found",
    serialNotFound: (s) => `No game found for serial \`${s}\`.`,
    gameNotFound: (q) => `No game found for “${q}”.`,
    error: "An error occurred.",
    games: "games",
    systems: "systems",
    lastUpdated: "Last updated",
    version: "Version",
    author: "Author",
    systemsField: "Systems",
    downloads: "Downloads",
    viewGame: "View game page",
    moreResults: (n) => `+ ${n} more result(s) — refine your search`,
    randomTitle: "Random game",
    statsTitle: "NDS-Shop stats",
    teamTitle: "NDS-Shop team",
    teamEmpty: "No registered members.",
    status: {
      online: "Online",
      idle: "Idle",
      dnd: "Do not disturb",
      offline: "Offline",
    },
    helpTitle: "NDS-Shop commands",
    suggestSent: "Suggestion sent to #suggestions!",
    reportSent: "Report sent to #bug-reports!",
    suggestTitle: "💡 Suggestion",
    reportTitle: "🐛 Bug report",
    byUser: "by",
    newGamesTitle: "🆕 New game available",
  },
};

// Langue selon le rôle du membre : English -> en, sinon fr (défaut)
function detectLang(member, guild) {
  if (!member) return "fr";
  const roles = member.roles?.cache;
  if (!roles) return "fr";
  if (roles.some((r) => r.name === "English")) return "en";
  return "fr";
}

module.exports = { T, detectLang };
